config/routes.rb
Rails.application.routes.draw do
  root to: "recipes#index"
  resources :recipes, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to recipes_path
    else
      flash.now[:error] = displayed_errors(@recipe)
      render :new
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name)
  end

  def displayed_errors(record)
    record.errors.full_messages.to_sentence
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>

    <%= yield %>
  </body>
</html>

app/views/recipes/_recipe.html.erb
<section>
  <p><%= recipe.name %></p>
</section>

app/views/recipes/index.html.erb
<%= render(@recipes) || "No recipes yet - get cooking" %>
<%= link_to "New Recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<%= form_for @recipe, url: recipes_path do |f| %>
  <%= f.label "name" %>
  <%= f.text_field :name %>
  <%= f.submit "Add To Cookbook" %>
<% end %>